GET http://127.0.0.1:8000/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTM4MDYzMDgsIm1lbWJlcl9pZCI6MCwicGVybWlzc2lvbiI6Im1lbWJlciJ9.JEKkvU2YLQUjntwwp3aJy5G2MjnIOrJeDevfaN8RKBM

###
POST http://127.0.0.1:8000/member/login
Content-Type: application/json

{
    "username": "John",
    "password": "test"
}
###

GET http://127.0.0.1:8000/book/0
Content-Type: application/json

###

GET http://127.0.0.1:8000/borrowing?id=0
Content-Type: application/json

###

POST http://127.0.0.1:8000/borrowing/create
Content-Type: application/json

{
    "member_id": 0,
    "unique_id": 20
}


###

POST http://127.0.0.1:8000/borrowing/set-status
Content-Type: application/json

{
    "borrow_id": 0,
    "status": "return"
}

###

POST http://127.0.0.1:8000/edit-book
Content-Type: application/json

{
        "book_id": 0,
        "title": "The Fault in Ours Stars",
        "genre": "Comedy",
        "author": "John Chowrai",
        "detail": "bra..brabra.."
}


###

POST http://127.0.0.1:8000/add-book
Content-Type: application/json

{
        "book_id": null,
        "title": "abc",
        "genre": null,
        "author": "author morgan",
        "detail": "description bra bra bra",
        "coverUrl": "www.asdas../asdaasd"
 }

###
GET http://127.0.0.1:8000/add-unique
Content-Type: application/json

 {
	"book_id" : 20,
	"unique_id" : null
 }

###
GET http://127.0.0.1:8000/member-data
Content-Type: application/json

 {
    "member_id":0
 }

###
GET http://127.0.0.1:8000/member-borrowing
Content-Type: application/json

{
    "member_id":0
}	

###
POST http://127.0.0.1:8000/member-borrowing/create
Content-Type: application/json

{
    "member_id": 0,
    "unique_id": 20
}