GET http://127.0.0.1:8000/borrowing?id=6
Content-Type: application/json

###

POST http://127.0.0.1:8000/borrowing/create
Content-Type: application/json

{
    "member_id": 0,
    "unique_id": 0
}


###

POST http://127.0.0.1:8000/borrowing/set-status
Content-Type: application/json

{
    "borrow_id": 6,
    "status": "return"
}